name: Main workflow

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'doc/**'
      - 'examples/**'
  push:
    paths-ignore:
      - '**.md'
      - 'doc/**'
      - 'examples/**'
  workflow_dispatch:

jobs:
  build:
    name: Build

    strategy:
      matrix:
        os: [ubuntu-20.04]
        ocaml: [4.12.0]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        id: cache-ocaml
        uses: actions/cache@v2
        with:
          path: ~/.opam
          key: v1-${{ matrix.os }}-ocaml.${{ matrix.ocaml }}-${{ hashFiles('**opam.locked') }}
          restore-keys: |
            v1-${{ matrix.os }}-ocaml.${{ matrix.ocaml }}-
            v1-${{ matrix.os }}-

      - name: Setup OCaml
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml }}

      - name: Install dependencies
        if: steps.cache-ocaml.outputs.cache-hit != 'true'
        run: opam install . --deps-only --locked

      - name: Format code
        run: opam exec -- dune build @fmt

      - name: Build
        run: opam exec -- dune build
